# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_goer', to='app.User'),
        ),
        migrations.AlterField(
            model_name='yourtrips',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='app.Trip'),
        ),
        migrations.AlterField(
            model_name='yourtrips',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_trip', to='app.User'),
        ),
    ]
