# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170728_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourtrips',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_object', to='app.Trip'),
        ),
    ]
