# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170728_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourTrips',
            new_name='YourTrip',
        ),
    ]
